language: python
python:
  - "3.3"
env:
  - DATABASE_URL=postgres://postgres:@127.0.0.1:5432/python.org
before_install:
  - sudo apt-get update -qq
install:
  - pip install --quiet --upgrade pip
  - pip install --quiet --use-mirrors -r requirements.txt
  - pip install --quiet --use-mirrors -r dev-requirements.txt
before_script:
  - psql -c 'create database "python.org";' -U postgres
script:
  - coverage run manage.py test
  - coverage report --fail-under=85
notifications:
    irc:
        channels:
            - "irc.freenode.net#revsys-hq"
        on_success: change
        on_failure: always
